version: '3.8'

services:
  order-service:
    build:
      context: ./order_service
    container_name: order-service-sync
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/orders_db

  payment-service:
    build:
      context: ./payment_service
    container_name: payment-service-sync
    ports:
      - "8002:8002"

  notification-service:
    build:
      context: ./notification_service
    container_name: notification-service-sync
    ports:
      - "8001:8001"

  postgres:
    image: postgres:13
    container_name: postgres-sync
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
