version: '3.8'

services:
  order-service:
    build:
      context: ./order_service
    container_name: order-service-sync
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/orders_db

  payment-service:
    build:
      context: ./payment_service
    container_name: payment-service-sync
    ports:
      - "8002:8002"

  notification-service:
    build:
      context: ./notification_service
    container_name: notification-service-sync
    ports:
      - "8001:8001"

  postgres:
    image: postgres:13
    container_name: postgres-sync
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus-sync
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana-sync
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana

  locust:
    image: locustio/locust
    container_name: locust-sync
    ports:
     - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host=http://order-service:8000

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data

  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data

  postgres_data:

  locust:

networks:
  default: 
    name: communication-performance-sync-network
